/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SS26
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    private void simpanPesanan(String email, String film, String jam, String kursi) {
        try (java.io.FileWriter writer = new java.io.FileWriter("pesanan.txt", true)) {
            writer.write(email + "," + film + "," + jam + "," + kursi + System.lineSeparator());
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
    
    private java.util.Set<String> getKursiTerisi(String film, String jam) {
        java.util.Set<String> terisi = new java.util.HashSet<>();
        try (java.util.Scanner scanner = new java.util.Scanner(new java.io.File("pesanan.txt"))) {
            while (scanner.hasNextLine()) {
                String[] data = scanner.nextLine().split(",");
                if (data.length == 4 && data[1].equals(film) && data[2].equals(jam)) {
                    terisi.add(data[3]);
                }
            }
        } catch (java.io.FileNotFoundException e) {
            // File belum ada, artinya belum ada kursi terisi
        }
        return terisi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanFilm = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pilihanJam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pilihanKursi = new javax.swing.JComboBox<>();
        btnPesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pilihanFilm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pilihanFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUMBO", "COCOTE TONGGO", "MUNGKIN KITA PERLU WAKTU", "PEMBANTAIAN DUKUN SANTET" }));
        pilihanFilm.setToolTipText("");
        pilihanFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanFilmActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setText("example@gmail.com");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Masukkan Email");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Film");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pilih Jam");

        pilihanJam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pilihanJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Jam", " " }));
        pilihanJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanJamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Pembelian Tiket Bioskop Online");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Pilih Kursi");

        pilihanKursi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pilihanKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kursi" }));

        btnPesan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pilihanJam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pilihanFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pilihanKursi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihanFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pilihanJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pilihanKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnPesan)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanFilmActionPerformed
        String selectedFilm = (String) pilihanFilm.getSelectedItem();

    // Bersihkan dulu isi jComboBox1
        pilihanJam.removeAllItems();

        if (selectedFilm == null) return;

    // Gunakan switch-case berdasarkan nama film
        switch (selectedFilm) {
            case "JUMBO":
                pilihanJam.addItem("09:30");
                pilihanJam.addItem("12:00");
                pilihanJam.addItem("14:30");
                pilihanJam.addItem("17:00");
                break;

            case "COCOTE TONGGO":
                pilihanJam.addItem("12:25");
                pilihanJam.addItem("16:30");
                pilihanJam.addItem("18:45");
                pilihanJam.addItem("21:00");
                break;

            case "MUNGKIN KITA PERLU WAKTU":
                pilihanJam.addItem("12:30");
                pilihanJam.addItem("16:00");
                pilihanJam.addItem("18:30");
                break;

            case "PEMBANTAIAN DUKUN SANTET":
                pilihanJam.addItem("19:30");
                pilihanJam.addItem("21:00");
                break;
        }
    }//GEN-LAST:event_pilihanFilmActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void pilihanJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanJamActionPerformed
        pilihanKursi.removeAllItems();

        String selectedFilm = (String) pilihanFilm.getSelectedItem();
        String selectedJam = (String) pilihanJam.getSelectedItem();

        if (selectedFilm == null || selectedJam == null) return;

        String[] semuaKursi = {"A1", "A2", "A3", "A4", "A5", "B1", "B2", "B3", "B4", "B5", "C1", "C2", "C3", "C4", "C5"};
        java.util.Set<String> kursiTerisi = getKursiTerisi(selectedFilm, selectedJam);

        for (String k : semuaKursi) {
            if (!kursiTerisi.contains(k)) {
                pilihanKursi.addItem(k);
            }
        }

        jLabel5.setVisible(true);
        pilihanKursi.setVisible(true);
    }//GEN-LAST:event_pilihanJamActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String email = jTextField1.getText();
                String film = (String) pilihanFilm.getSelectedItem();
                String jam = (String) pilihanJam.getSelectedItem();
                String kursi = (String) pilihanKursi.getSelectedItem();

                if (email.isEmpty() || film == null || jam == "Pilihan Jam" || kursi == "Pilihan Kursi") {
                    javax.swing.JOptionPane.showMessageDialog(null, "Lengkapi semua data terlebih dahulu!");
                    return;
                }

                // Cek apakah kursi sudah terisi (validasi ganda)
                if (getKursiTerisi(film, jam).contains(kursi)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Kursi sudah dipesan! Silakan pilih kursi lain.");
                    return;
                }

                simpanPesanan(email, film, jam, kursi);
                javax.swing.JOptionPane.showMessageDialog(null, "Tiket berhasil dipesan!\nFilm: " + email + "\nEmail: " + film + "\nJam: " + jam + "\nKursi: " + kursi);
            }
        });
    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> pilihanFilm;
    private javax.swing.JComboBox<String> pilihanJam;
    private javax.swing.JComboBox<String> pilihanKursi;
    // End of variables declaration//GEN-END:variables
}
